# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Shifty' do

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'SwiftDate'

end

target 'ShiftyTests' do

end

